config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :properties do
    resources :interests, only: [:index, :create, :destroy]
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user

  has_many :interests, dependent: :destroy

  validates :title, :price, presence: true, length: { maximum: 50 }
  validates :property_size , presence: true
  validates :is_deposit_required , presence: true

  def interest_shown_by?(user)
    user_intreset(user).present?
  end

  def user_intreset(user)
    self.interests.find_by(user_id: user.id)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_property, only: %i[show edit update destroy]

  def index
    @properties = current_user.broker? ? current_user.properties : Property.all
  end

  def show
  end

  def new
    @property = Property.new
  end

  def edit
  end

  def create
    @property = Property.new(property_params.merge(user_id: current_user.id))

    if @property.save
      redirect_to property_url(@property), notice: "Property was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @property.update(property_params)
      redirect_to property_url(@property), notice: "Property was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @property.destroy

    redirect_to properties_url, notice: "Property was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:title, :property_size, :price, :is_deposit_required)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<br>
  <div class="field">
    <%= form.label :property_size %>
    <%= form.number_field :property_size %>
  </div>
<br>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
<br>
  <div class="field">
    <%= form.label :is_deposit_required %>
    <%= form.check_box :is_deposit_required %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<div class= "contanier my-3">
  <% if current_user.broker? %>
    <%= link_to "Create New Property", new_property_path, class: "btn btn-primary" %> 
  <% end %>

  <hr>

  <div class="row mx-0">
    <% @properties.each do |p|%>
      <div class="col-md-3 my-2">
      <div class="card">
      <div class="card-body">
        <h5 style="color :black;" class="card-title"><%= p.title%></h5>
        <h6 style="color :black;"> <p class="card-text">
          <p> Property Size : <%= p.property_size %> </p><br>
          <p> Price : <%= p.price %></p><br>
          <p> Is deposit required? : <%= p.is_deposit_required %></p>
          <p> Created by: <%= p.user.name.capitalize %> </p>
          <%= link_to "View", property_path(p), class:"btn btn-primary"%>
          </p>
        </h6>
      </div>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @property.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<p>
  <strong>Property size:</strong>
  <%= @property.property_size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Is deposit required:</strong>
  <%= @property.is_deposit_required %>
</p>

<%= link_to 'Back', properties_path, class: "btn btn-primary"  %>

<% if current_user.broker? %>
  <%= link_to "Show Interested User", property_interests_path(@property), class: "btn btn-primary" %>
  <%= link_to 'Edit' , edit_property_path(@property), class: "btn btn-primary"  %>
  <%= link_to 'Destroy', property_path(@property), method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-primary" %>
<% else %>
  <% if @property.interest_shown_by?(current_user) %>
    <%= button_to 'Cancel', property_interest_path(property_id: @property.id, id: @property.user_intreset(current_user).id), method: :delete %>
  <% else %>
    <%= button_to 'Interest', property_interests_path(@property), method: :post %>
  <% end %>
<% end %>

</div>